version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'
    volumes:
      - initialize_database.sql /docker-entrypoint-initdb.d/


  movies:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db